controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_analytics:
    path: /count
    controller: App\Controller\AnalyticsController::index
    methods: [GET]